### ISSUE TITLE
Your Solution for Day 8 does not compile on HackerRank

### ISSUE THREAD

**Issue by Angr1st** [mxwsxr/HackerRankCodingChallenge#10]
yo boi, it does not compile.

**Comment by mxwsxr** [comment]
> yo boi, it does not compile.

Their compiling give me headaches, why do they give me an error when there is a newline in the end? How do I remove that newline? (Console.Write() doesnt work at this)

**Comment by Angr1st** [comment]
Moin Alberto, If you want we can have a look at it together tomorrow night.

Albert <notifications@github.com> schrieb am So., 27. Okt. 2019, 21:12:

**Comment by Angr1st** [comment]
Hi Albert you havent created a pr to fix this.
