### ISSUE TITLE
Write your own array reversing 

### ISSUE THREAD

**Issue by Angr1st** [mxwsxr/HackerRankCodingChallenge#5]
Hoi Alberto,

could you instead of using Array.reverse build your own array reversing function? (Specifically for Day 7)

**Comment by mxwsxr** [comment]
I made an attempt writing my own Reverse function by adding a new Helper class and invoking it in my main class. After building and running my project it did work with any given input. Maybe you'll find something more specific for improving my code, thanks and have a good day!

**Comment by Angr1st** [comment]
Please use your own head and don't just copy it from the C# Cookbook Page 208 thanks, Alberto
